<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $menuData = $menuHelper->getMenuData(); extract($menuData); ?>
<?php 
$legendaHelper = Mage::helper('legenda'); 
$menuType = $legendaHelper->getConfig('header_settings/header_type'); 
?>
<div class="header-wrapper <?php echo $menuType ?>">
<!--<div class="container">
    <div class="menu-icon hidden-md hidden-lg"><i class="fa fa-bars"></i></div>
</div>-->

<div class="main-nav visible-md visible-lg">
    <div class="double-border">
        <div class="container">            
            <div class="menu-wrapper">
                <div class="logo-with-menu">
                    <?php if ($menuHelper->getIsHomePage()):?>
                    <h1 class="logo"><strong><?php echo $menuHelper->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $menuHelper->getLogoAlt() ?>"><img src="<?php echo $menuHelper->getLogoSrc() ?>" alt="<?php echo $menuHelper->getLogoAlt() ?>" /></a></h1>
                    <?php else:?>
                        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $menuHelper->getLogoAlt() ?>" class="logo"><strong><?php echo $menuHelper->getLogoAlt() ?></strong><img src="<?php echo $menuHelper->getLogoSrc() ?>" alt="<?php echo $menuHelper->getLogoAlt() ?>" /></a>
                    <?php endif?>
                </div>
                <div class="menu-all-pages-container">
                    <ul class="menu" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement" role="navigation">
                        <?php echo $menuHelper->getMenuContent(); ?>
                       
                        <li><div style="width: 150px;"><a itemprop="url" href="/quiz-nov/"><span style="display:none" itemprop="name">What is Right for You</span><img style="width:100%;" alt="Waht is Right for You" src="/what_is_right_.png"}} /></a></div></li>
                    </ul>
                    
                
                    
                </div>
            </div>
        </div>
    </div>
</div>

</div>

<script type="text/javascript">
//<![CDATA[
var SW_MENU_POPUP_WIDTH = <?php echo $_popupWidth; ?>;
//]]>
</script>